language: python
python:
  - "3.5"
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
dist: xenial
sudo: true
# command to install dependencies
install:
  - pip install -U tensorflow>=2.0.0
  - pip install -U .
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
